services:
  backend:
    build: ./server
    ports:
      - "5001:5000"
    env_file:
      - ./server/.env
    volumes:
      - ./server:/app
      - /app/node_modules
    depends_on:
      - db
    command: npm run dev

  frontend:
    build: ./client
    ports:
      - "3001:3000"
    volumes:
      - ./client:/app
      - /app/node_modules
    stdin_open: true
    command: npm run dev

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: patient_db
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
